<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.simple_form.main' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php';

return $this->services['security.authentication.provider.simple_form.main'] = new \Symfony\Component\Security\Core\Authentication\Provider\SimpleAuthenticationProvider(${($_ = isset($this->services['AppBundle\Security\PasswordAuthenticator']) ? $this->services['AppBundle\Security\PasswordAuthenticator'] : $this->load(__DIR__.'/getPasswordAuthenticatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.user.provider.concrete.my_db_provider']) ? $this->services['security.user.provider.concrete.my_db_provider'] : $this->load(__DIR__.'/getSecurity_User_Provider_Concrete_MyDbProviderService.php')) && false ?: '_'}, 'main');
