# services to handle doctrine extensions
# import it in config.yml
services:
    # Doctrine Extension listeners to handle behaviors
    gedmo.listener.iptraceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]