<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Security\PasswordAuthenticator' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/SimpleAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Authentication/SimpleFormAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/Security/PasswordAuthenticator.php';

return $this->services['AppBundle\Security\PasswordAuthenticator'] = new \AppBundle\Security\PasswordAuthenticator(${($_ = isset($this->services['security.password_encoder']) ? $this->services['security.password_encoder'] : $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php')) && false ?: '_'});
